name: Check openvino2onnx coding style
run-name: ${{ github.actor }} linting
on:
  pull_request:
    paths:
      - 'openvino2onnx/**.py'
      - 'tests/**.py'
jobs:
  run-flake8:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          python -m pip install pre-commit
          pre-commit install --install-hooks
      - name: lint with pre-commit
        # check all commits from main
        run: pre-commit run -s HEAD^ -o HEAD
  run-pyright:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/Jod
      - name: pyright type check
        run: |
          python -m pip install -U pyright
          python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          python -m pip install onnxscript onnxruntime openvino onnxoptimizer onnxsim colorlog
          python -m pip install -e .
          pyright openvino2onnx
